version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: skillhub-jenkins
    ports:
      - "8081:8080" 
    volumes:
      - jenkins_home:/var/jenkins_home
      - //var/run/docker.sock:/var/run/docker.sock
      # Mount the project root so Jenkins can access the local Git repo
      - ../:/var/skillhub-source
    user: root 
    restart: unless-stopped

volumes:
  jenkins_home:
